### ISSUE TITLE
Collecting Raw Data

### ISSUE THREAD

**Issue by antra0497** [CapstoneProject18/House-Price-Predicting-Model#4]
We have collected raw-data from Kaggle database keeping in mind all the requirements.

It contains sales price and its features for houses sold in north American countries between 2014 to 2015. 
There are 21,614 observations in the dataset, with 21 attributes in total: including Latitude and Longitude information ( Area, Floors, Balconies, Bathrooms etc.)

**Comment by bhaduriu** [comment]
If possible we have to find similar dataset for Indian Geography.
